### ISSUE TITLE
Documenta algún método con javadoc

### ISSUE THREAD

**Issue by iordic** [iordic/Jacktoberfest2016#12]
Añade algún comentario para explicar que hace uno de los métodos. Por ejemplo:

``` java
    /**
     * Devuelve la cantidad de pull requests realizados por el usuario.
     * @return número de PRs
     */
    public int getTotalRequests() {
        ...
    }
```

**Comment by jpitchardu** [comment]
Tan facil, ok.

**Comment by iordic** [comment]
Ahí esta la gracia. 😺 👍  Así la gente que le queda algun PR por hacer puede hacerlo.

**Comment by iordic** [comment]
También puedes hacer alguno de los dos métodos si te parece fácil. 😄

**Comment by jpitchardu** [comment]
Gracias @iordic, me faltaban dos porque estuve muy ocupado.

**Comment by iordic** [comment]
¡Se acabó octubre! Cierro el issue.
